pybo/views/answer_views.py
from datetime import datetime
from importlib.resources import contents

from flask import Blueprint, request, redirect, url_for, render_template, g, flash
from pybo import db
from pybo.forms import AnswerForm
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=["POST"])
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form.get('content')
        # answer = Answer(content=content, create_date=datetime.now())
        # question.answers.append(answer)
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answers_set.append(answer)
        db.session.add(answer)
        db.session.commit()

        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:answer_id>/', methods=['GET', 'POST'])
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=answer.question_id))
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question_id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html',form=form)

@bp.route('/delete/<int:answer_id>/')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question._list'))

pybo/views/question_views.py
import os
from datetime import datetime

from flask import Blueprint, render_template, request, redirect, url_for, g, flash, current_app
from werkzeug.utils import secure_filename

from pybo import db
from pybo.forms import QuestionForm, AnswerForm
from pybo.models import Question, Answer, User
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list():
    page = request.args.get('page', default=1, type=int) # 페이지
    kw = request.args.get('kw', default=None, type=str)  # 검색어 키워드 추가
    question_list = Question.query.order_by(Question.create_date.desc())
    if kw:
        search = f'%%{kw}%%'
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list.join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |  # 질문제목
                    Question.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()
    question_list = question_list.paginate(page=page, per_page=10) # 한페이지에 보여야할 게시물
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm() # 질문 상세 템플릿에 답변 폼 추가
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        # 폼에서 받은 이미지 파일 처리
        image_file = form.image.data # 폼에 있는 이미지 파일
        image_path = None

        if image_file:
            # 저장 경로 설정 : 오느 날짜 폴더 생성
            today = datetime.now().strftime('%Y%m%d')
            # 업로드 폴더 경로 지정 = 어디에 저장을 할것인가
            upload_folder = os.path.join(current_app.root_path, 'static/photo', today)
            os.makedirs(upload_folder, exist_ok=True)

            # 파일 저장
            filename = secure_filename(image_file.filename)
            file_path = os.path.join(upload_folder, filename)
            image_file.save(file_path)

            # DB에 저장할 경로 (static 기준 상대경로)
            image_path = f'photo/{today}/{filename}'


        question = Question(
            subject=form.subject.data,
            content=form.content.data,
            create_date=datetime.now(),
            user=g.user,
            image_path=image_path
        )

        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html',form=form)

@bp.route('/modify/<int:question_id>', methods=['GET', 'POST'])
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정 권한이 없습니다.') # 강제로 에러발생 시킴
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else: # get 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>/')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    else:
        db.session.delete(question)
        db.session.commit()
    return redirect(url_for('question._list'))

pybo/templates/question/question_detail.html
{% extends 'base.html'%}
{% block content %}


<div class="container my-3">
    <!--flash 오류-->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">
                {{question.content}}                
            </div>
            
            <!--첨부 파일 이미지가 있을 경우에만 동작 -->
            {% if question.image_path %}
            <div class="my-3">
                <img src="{{ url_for('static', filename=question.image_path) }}" alt="첨부 이미지"
                        style="max-width: 100%; height: auto;" class="img-thumbnail">
            </div>
            {% endif %}
            
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">modified at</p>
                    <p class="mb-2">{{ question.modify_date|datetime }}</p>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">{{question.user.username}}</p>
                    <p class="mb-2">{{ question.create_date | datetime }}</p>
                </div>
            </div>
            <div class="my-3">
                {% if g.user == question.user %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <button class="btn btn-sm btn-outline-danger delete"
                        data-uri="{{ url_for('question.delete', question_id=question.id)}}">삭제
                </button>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- 답변 내용 -->
    <h5 class="border-bottom my-3 py-2">{{ question.answers_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answers_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">modified at</p>
                    <p class="mb-2">{{ answer.modify_date|datetime }}</p>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <p class="mb-2">{{answer.user.username}}</p>
                    <p class="mb-2">{{ answer.create_date | datetime }}</p>
                </div>
            </div>
            <div class="my-3">
                {% if g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <button class="btn btn-sm btn-outline-danger delete"
                        data-uri="{{ url_for('answer.delete', answer_id=answer.id)}}">삭제
                </button>

                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!--    답변등록-->
    <form action="{{ url_for('answer.create', question_id=question.id)}}" method="post">
        {% include 'form_errors.html' %}

        <textarea {% if not g.user %} disabled {% endif%}
                  class="form-control" name="content" id="content" rows="15"></textarea>
        <button type="submit" class="bth bth-primaty mt-3" {% if not g.user %} disabled {% endif%}>답변등록</button>

    </form>
</div>
{% endblock %}

{% block script %}
<script>
    const delete_elements = document.querySelectorAll('.delete');
    delete_elements.forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm('정말로 삭제하시겠습니까?')) {
                location.href = this.dataset.uri;
            }
        })
    })

</script>

{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html'%}
{% block content %}
<!--질문등록-->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="my-3" enctype="multipart/form-data"> <!-- 파일을 업로드 할경우 enctype="multipart/form-data" 필수 입력 -->
        {% include 'form_errors.html' %}
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" name="subject" id="subject" class="form-control" value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea name="content" id="content" rows="5" class="form-control">{{ form.content.data or '' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="image">이미지 첨부</label>
            <input type="file" name="image" id="image" class="form-control">
        </div>


<!--    {{ form.subject.label }}-->
<!--    {{ form.subject(class='form-control') }}-->

<!--    {{ form.content.label }}-->
<!--    {{ form.content(class='form-control') }}-->
    <button type="submit" class="btn btn-primary">저장하기</button>
   </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html'%}
{% block content %}

<div class="container my-3">
    <!--검색기능 추가-->
    <div class="row my-3">
        <div class="col-6">
            <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control"
                       value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr class="table-dark">
            <th scope="col">번호</th>
            <th scope="col">제목</th>
            <th scope="col">글쓴이</th>
            <th scope="col">작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{question_list.total - (question_list.page -1) * question_list.per_page - loop.index0}}</td>
            <td>
                <!--글 리스트에서 썸네일 표시 하는 방법 (if 문 필수로 작성해야함)-->
                {% if question.image_path %}
                    <img src="{{ url_for('static', filename=question.image_path) }}" alt="썸네일" style="width: 50px">
                    {% endif %}

                <a href="{{ url_for('question.detail', question_id=question.id) }}/">{{question.subject}}</a>


                {% if question.answers_set|length>0 %}
                <span class="text-danger small mx-2">[{{ question.answers_set|length }}]</span>
                {% endif %}
            </td>
            <td>{{question.user.username}}</td>
            <td>{{ question.create_date | datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--    페이징처리 시작-->
    <ul class="pagination justify-content-center">
        <!--        이전버튼-->
        {% if question_list.has_prev %}
        <li class="page-item"><a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="javascript:void(0)">이전</a></li>
        {% endif %}
        <!--페이지번호  -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        <!--일반페이지-->
        {% if page_num != question_list.page%}
        <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{ page_num }}">{{page_num}}</a>
        </li>
        <!--현재페이지-->
        {%else%}
        <li class="page-item active"><a class="page-link" aria-current="page" href="javascript:void(0)">{{page_num}}</a>
        </li>
        {%endif%}
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="javascript:void(0)">...</a></li>
        {% endif %}
        {% endfor %}

        <!--다음버튼-->
        {% if question_list.has_next %}
        <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="javascript:void(0)">다음<</a></li>
        {% endif %}
    </ul>

    <form id="searchForm" action="{{url_for('question._list')}}" method="get">
        <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
    <!--    페이징 처리 종료-->
    <a href="{{url_for('question.create')}}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}


{% block script %}
<script>
    // 페이지 버튼
    const page_elements = document.querySelectorAll('.page-link');
    page_elements.forEach(element => {
        element.addEventListener('click', function () {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    // 검색버튼 클릭시 동작
    const btn_search = document.getElementById('btn_search');
    btn_search.addEventListener('click', () => {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1로 초기화
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}